# ==========================================
# SafeSight Configuration
# ==========================================

pipeline:
  device: "cuda"  # ou "cpu"
  frame_resize: [640, 480]  # optionnel, pour YOLO/SAM

detection:
    model_path: "models/yolov8n-seg.pt"  # modèle fine-tuné
    confidence_threshold: 0.3

depth:
  model_path: "models/midas_v21_384.pt"

classes:
  - cable_electrique
  - multiprise
  - meuble_instable
  - produit_menager
  - jouet_petits_pieces
  - radiateur
  - coin_meuble

llm:
  model_name: "gemini-2.5-flash"
  max_tokens: 200
  temperature: 0.2
